---
swagger: "2.0"
info:
  description: "Api de Produto"
  version: "1.0.0"
  title: "Swagger Produto"
  contact:
    email: "contato@email.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:8080
basePath: "/v2"
tags:
- name: "configuracoes"
  description: "Operações de configuração do microserviço"
- name: "produtos"
  description: "Operações de Produto"
schemes:
- "https"
- "http"
paths:
  /ping:
    get:
      tags:
      - "configuracoes"
      summary: "Api keepalive"
      description: "Api keepalive"
      operationId: "get_alive"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "pong response"
      x-swagger-router-controller: "swagger_server.controllers.configuracoes_controller"

  /usuarios:
    post:
      tags:
      - "usuarios"
      summary: "Cria usuario"
      description: "cria usuario"
      operationId: "post_cria_usuario"
      produces:
      - "application/json"
      parameters:
      - name: "usuario"
        in: "body"
        description: "Cria um um usuario no banco de dados"
        schema:
          type: object
          required:
            - usuario
            - senha
            - nome
            - email
          properties:
            usuario:
              type: string
            senha:
              type: string
            nome:
              type: string
            email:
              type: string
            instituicao:
              type: string
      responses:
        "200":
          description: "usuario criado"
          schema:
            $ref: "#/definitions/Usuario"
        "204":
          description: "Quando não há dados na dase de dados para retorno"
        "500":
          description: "Erro no servidor"
      security:
      - apiKey: []
      x-swagger-router-controller: "swagger_server.controllers.usuarios_controller"

  /coordenadas:
    post:
      tags:
      - "coordenadas"
      summary: "Cria uma coordenada"
      description: "cria coordenada"
      operationId: "post_cria_coordenada"
      produces:
      - "application/json"
      parameters:
      - name: "coordenada"
        in: "body"
        description: "Body necessario para criacao de uma coordenada"
        schema:
          type: object
          required:
            - id_usuario
            - lat
            - lon
            - nm_local
            - indice_radiacao
          properties:
            id_usuario:
              type: integer
              example: 1
            lat:
              type: number
              example: -22.00034
            lon:
              type: number
              example: 44.00068
            nm_local:
              type: string
              example: Morro dos Ventos
            indice_radiacao:
              type: number
              example: 0.1
      responses:
        "200":
          description: "usuario criado"
          schema:
            $ref: "#/definitions/Coordenada"
        "204":
          description: "Quando não há dados na dase ed dados para retorno"
        "500":
          description: "Erro no servidor"
      security:
      - apiKey: []
      x-swagger-router-controller: "swagger_server.controllers.coordenadas_controller"
    get:
      tags:
      - "coordenadas"
      summary: "retorna uma lista com todas as coordenadas cadastrada no sistema"
      description: "retorna uma lista com todas as coordenadas cadastrada no sistema"
      operationId: "get_lista_coordenadas"
      produces:
      - "application/json"
      responses:
        "200":
          description: "lista de coordenadas"
          schema:
            $ref: "#/definitions/ListaCoordenada"
        "204":
          description: "Quando não há dados na dase ed dados para retorno"
        "500":
          description: "Erro no servidor"
      security:
      - apiKey: []
      x-swagger-router-controller: "swagger_server.controllers.coordenadas_controller"

securityDefinitions:
  apiKey:
    description: "jwt cross-token generated by authentication api"
    type: "apiKey"
    name: "x-api-key"
    in: "header"
    x-apiKeyInfoFunc: ""
definitions:
  Usuario:
    type: "object"
    properties:
      usuario:
        type: string
      senha:
        type: string
      nome:
        type: string
      email:
        type: string
      instituicao:
        type: string
  Coordenada:
    type: "object"
    properties:
            id_usuario:
              type: integer
              example: 1
            lat:
              type: number
              example: -22.00034
            lon:
              type: number
              example: 44.00068
            nm_local:
              type: string
              example: Morro dos Ventos
            indice_radiacao:
              type: number
              example: 0.1
  ListaCoordenada:
    type: array
    items:
      $ref: "#/definitions/Coordenada"
parameters:
  XApiToken:
    name: "x-api-key"
    in: "header"
    required: false
    type: "string"
  query_nome:
    name: "nome"
    in: "query"
    description: "Busca pelo nome"
    required: false
    type: "string"
  query_pagina:
    name: "pagina"
    in: "query"
    description: "Paginação do resultado"
    required: false
    type: "integer"
