---
swagger: "2.0"
info:
  description: "Api de Produto"
  version: "1.0.0"
  title: "Swagger Produto"
  contact:
    email: "contato@email.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:8080
basePath: "/v2"
tags:
- name: "configuracoes"
  description: "Operações de configuração do microserviço"
- name: "produtos"
  description: "Operações de Produto"
schemes:
- "https"
- "http"
paths:
  /ping:
    get:
      tags:
      - "configuracoes"
      summary: "Api keepalive"
      description: "Api keepalive"
      operationId: "get_alive"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "pong response"
      x-swagger-router-controller: "swagger_server.controllers.configuracoes_controller"
  /produtos:
    get:
      tags:
      - "produtos"
      summary: "Retorna lista de produtos completa"
      description: "Retorna lista de produtos completa"
      operationId: "get_lista_produtos"
      produces:
      - "application/json"
      parameters:
      - name: "black_friday"
        in: "query"
        description: "Busca por produtos que fazem parte da Black Friday"
        required: false
        type: "boolean"
      responses:
        "200":
          description: "retorna Produto com Id especificado"
          schema:
            $ref: "#/definitions/ProdutoVO"
        "204":
          description: "Quando não há dados na dase ed dados para retorno"
        "500":
          description: "Erro no servidor"
      security:
      - apiKey: []
      x-swagger-router-controller: "swagger_server.controllers.produtos_controller"
  /produtos/{id_produto}:
    get:
      tags:
      - "produtos"
      summary: "Retorna produto por ID"
      description: "Retorna produto por ID"
      operationId: "get_produto_por_id"
      produces:
      - "application/json"
      parameters:
      - name: "id_produto"
        in: "path"
        description: "Busca por tabela_origem_dominio do domínio"
        required: true
        type: "integer"
      responses:
        "200":
          description: "retorna Produto com Id especificado"
          schema:
            $ref: "#/definitions/Produto"
        "204":
          description: "Quando não há produto com o Id especificado na base de dados"
        "500":
          description: "Erro no servidor"
      security:
      - apiKey: []
      x-swagger-router-controller: "swagger_server.controllers.produtos_controller"
securityDefinitions:
  apiKey:
    description: "jwt cross-token generated by authentication api"
    type: "apiKey"
    name: "x-api-key"
    in: "header"
    x-apiKeyInfoFunc: ""
definitions:
  Produto:
    type: "object"
    properties:
      brinde:
        type: "integer"
        example: 2
      oferta:
        type: "boolean"
        example: false
      oferta_inicio:
        type: "boolean"
        example: true
      menus:
        $ref: "#/definitions/Menu"
      menu:
        type: "integer"
        example: 100
      codigo:
        type: "integer"
        example: 50
      nome:
        type: "integer"
        example: 2
      familia:
        $ref: "#/definitions/Familia"
      fotos:
        type: "string"
      disponibilidade:
        type: "boolean"
      fabricante:
        $ref: "#/definitions/Fabricante"
      preco:
        type: "integer"
      preco_desconto:
        type: "integer"
      preco_desconto_prime:
        type: "integer"
      preco_antigo:
        type: "integer"
      economize_prime:
        type: "integer"
      descricao:
        type: "string"
      tag_title:
        type: "string"
      tem_frete_gratis:
        type: "boolean"
      frete_gratis_somente_prime:
        type: "boolean"
      tag_description:
        type: "string"
      avaliacao_numero:
        type: "integer"
      avaliacao_nota:
        type: "integer"
      desconto:
        type: "number"
      is_openbox:
        type: "boolean"
      produto_html:
        type: "string"
      dimensao_peso:
        type: "integer"
      peso:
        type: "string"
      garantia:
        type: "string"
      codigo_anatel:
        type: "string"
      produto_especie:
        type: "number"
      link_descricao:
        type: "string"
      origem:
        type: "string"
      origem_nome:
        type: "string"
      flag_blackfriday:
        type: "integer"
      sucesso:
        type: "boolean"
    example:
      economize_prime: 2
      brinde: 2
      oferta_inicio: true
      desconto: 3.61607674925191080461672754609026014804840087890625
      produto_html: "produto_html"
      oferta: false
      origem: "origem"
      preco_desconto: 1
      is_openbox: true
      garantia: "garantia"
      preco: 6
      tag_title: "tag_title"
      tag_description: "tag_description"
      preco_desconto_prime: 5
      menus: ""
      produto_especie: 4.1456080298839363962315474054776132106781005859375
      codigo: 50
      origem_nome: "origem_nome"
      disponibilidade: true
      avaliacao_nota: 9
      peso: "peso"
      link_descricao: "link_descricao"
      preco_antigo: 5
      dimensao_peso: 2
      codigo_anatel: "codigo_anatel"
      nome: 2
      frete_gratis_somente_prime: true
      menu: 100
      flag_blackfriday: 7
      descricao: "descricao"
      tem_frete_gratis: true
      fabricante:
        codigo: 0
        img: "img"
        nome: "nome"
      sucesso: true
      familia: ""
      fotos: "fotos"
      avaliacao_numero: 7
  ProdutoVO:
    type: "array"
    items:
      $ref: "#/definitions/Produto"
  Menu:
    type: "array"
    items:
      $ref: "#/definitions/Menu_inner"
  Familia:
    type: "array"
    items:
      $ref: "#/definitions/Familia_inner"
  Fabricante:
    type: "object"
    properties:
      codigo:
        type: "integer"
      nome:
        type: "string"
      img:
        type: "string"
    example:
      codigo: 0
      img: "img"
      nome: "nome"
  Menu_inner:
    type: "object"
    properties:
      codigo:
        type: "integer"
      nome:
        type: "string"
      amigavel:
        type: "string"
      nome_url:
        type: "string"
  Familia_inner_produtos:
    type: "object"
    properties:
      nome:
        type: "string"
      preco:
        type: "string"
      preco_prime:
        type: "string"
      preco_antigo:
        type: "string"
      disponibilidade:
        type: "string"
      preco_desconto:
        type: "string"
      preco_desconto_prime:
        type: "string"
      link_descricao:
        type: "string"
      foto:
        type: "string"
      produto_prime:
        type: "string"
  Familia_inner:
    type: "object"
    properties:
      codigo:
        type: "integer"
      nome:
        type: "string"
      titulo:
        type: "string"
      produtos:
        type: "array"
        items:
          $ref: "#/definitions/Familia_inner_produtos"
parameters:
  XApiToken:
    name: "x-api-key"
    in: "header"
    required: false
    type: "string"
  query_nome:
    name: "nome"
    in: "query"
    description: "Busca pelo nome"
    required: false
    type: "string"
  query_pagina:
    name: "pagina"
    in: "query"
    description: "Paginação do resultado"
    required: false
    type: "integer"
